<?php
/**
 * Name:
 * User: Kitty.Cheng
 * Mail: kitty.cheng@18php.com
 * Date: 2020/3/25
 * Time: 下午11:47
 * Created by 18php.com
 */

namespace app\index\controller;


use app\common\controller\BaseController;
use app\facade\ArticleCateModel;
use app\facade\SiteConfigModel;
use think\facade\Cache;

class Base extends BaseController
{
    protected $siteConfig;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // $this->siteConfig = Cache::get('site_config');
        // if(!$this->siteConfig){
        //     $this->siteConfig = SiteConfigModel::getInfo(1);
        //     Cache::set('site_config',$this->siteConfig,86400);
        // }
        $this->siteConfig = SiteConfigModel::getInfo(1);

        // $articleCateList = Cache::get('article_cate_list');
        // if(!$articleCateList){
        //     $articleCateList = ArticleCateModel::getListAll();
        //     Cache::set('article_cate_list',$articleCateList,86400);
        // }
        $articleCateList = ArticleCateModel::getListAll();

        $this->assign('siteConfig', $this->siteConfig);
        $this->assign('articleCateList', $articleCateList);
    }

    public function __call($name, $arguments)
    {
        return 'base error:'.$name;
    }
}