<?php
/**
 * Name:
 * User: Kitty.Cheng
 * Mail: kitty.cheng@18php.com
 * Date: 2020/3/25
 * Time: 下午11:47
 * Created by 18php.com
 */

namespace app\index\controller;


use app\common\controller\BaseController;
use app\facade\ArticleCateModel;
use app\facade\ArticleModel;

class Base extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $articleCateList = ArticleCateModel::getListAll();
        $this->assign('articleCateList', $articleCateList);
    }

    public function __call($name, $arguments)
    {
        return 'base error:'.$name;
    }
}